### PR TITLE
add validateNel function: returns NonEmptyList<String>

### PR DESCRIPTION
**Pull request by clojj**
This left-type plays more nicely with Arrow, just added it as an additional option

### CODE REVIEW

**Comment by clojj** [comment]
The name of validateNel maybe can be improved.. but I could not come up with a better one yet.
If the name can be finalized, it should also add an example and mention it in the readme

**Comment by clojj** [comment]
mentioned `validateNel` in README

**Comment by rcapraro** [comment]
Hi,
thx for the pull request 👍🏻 
i agree that `ValidatedNel` plays nicely with Arrow, but i prefer to return a `NonEmptyList<ValidationResult>` because it let the caller choose what format he wants (String, or a more structured message by parsing the `ValidationResult` class)

**Comment by clojj** [comment]
Hi Richard,
good point 
Will push another commit, also including a unit test

**Comment by clojj** [comment]
also I found that the dependency to
    implementation("org.apache.commons:commons-jexl3:3.1")
can be removed.

**Comment by rcapraro** [comment]
Many thanks for the pull request !

**Pull request merged**
